1 задание(функция sum)
js-tasks-ru/jsbasic-20240520_grevermain pull request #1
Opened 2024-05-20 18:40 UTC by greverXD

2024-05-20 18:40 UTC, jsru-1 commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2024-05-20 21:07 UTC, SinimaWath requested changes

2024-05-20 21:07 UTC, SinimaWath commented on 0-module/1-task/index.js
> +sum(2,5);
В файле с задачей должна быть только задача. Убери вызовы sum, пожалуйста ;)

2024-05-20 21:07 UTC, SinimaWath commented on 0-module/1-task/index.js
> +  console.log(m + n);
Функция должна возвращать результат через `return m + n`. Давай поправим

2024-05-24 18:11 UTC, SinimaWath approved these changes

2024-05-24 18:11 UTC, merged